In [1]:
import numpy as np
import time

a = np.random.rand(2000000)
b = np.random.randn(2000000)


#Vectorization method
toc = time.time()
k = np.dot(a,b)

tic = time.time()
print("Vectorization technique has result = %d" % k)
print(str(1000*(tic-toc))+"ms")


#Non-vectorization method
p = 0
toc = time.time()
for i in range(2000000):
    
    p += a[i]*b[i]
    
tic = time.time()

print("Non-Vectorization technique has result = %d" % p)
print(str(1000*(tic-toc))+"ms")



Vectorization technique has result = -1091
0.9748935699462891ms
Non-Vectorization technique has result = -1091
812.335729598999ms


In [2]:
a.size


2000000

In [10]:
a.shape


(2000000,)

In [16]:
a = np.random.randn(4,3) # a.shape = (4, 3)

In [17]:
a.shape = (4, 3)

In [20]:
b = np.random.randn(1, 3) # b.shape = (3, 2)

In [21]:
c = a*b


In [22]:
c

array([[-0.26201013, -0.53636263, -0.66386157],
       [-0.14298923,  0.29667989,  0.39818495],
       [-0.36090266, -0.72395682, -0.65662429],
       [-0.23356516,  0.7611747 ,  0.059032  ]])

In [25]:
k = np.random.rand(5,4)

In [26]:
k

array([[0.32372405, 0.48609574, 0.15948848, 0.92046739],
       [0.5230761 , 0.85157947, 0.4958025 , 0.965798  ],
       [0.35740186, 0.62315118, 0.10957751, 0.2794302 ],
       [0.38970967, 0.73167075, 0.34063451, 0.12525666],
       [0.78316992, 0.14071915, 0.45180271, 0.65334289]])

In [27]:
k.reshape(2,10)

array([[0.32372405, 0.48609574, 0.15948848, 0.92046739, 0.5230761 ,
        0.85157947, 0.4958025 , 0.965798  , 0.35740186, 0.62315118],
       [0.10957751, 0.2794302 , 0.38970967, 0.73167075, 0.34063451,
        0.12525666, 0.78316992, 0.14071915, 0.45180271, 0.65334289]])

In [30]:
new = np.random.randint(4,size = (4,4,3))

In [31]:
new.shape


(4, 4, 3)

In [32]:
new.shape[0]

4

In [33]:
new.shape[1]

4

In [34]:
new.shape[2]

3